server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_banking?currentSchema=microbanking

    username: root
    password: Mysql21
  jpa:
    hibernate:
      ddl-auto: update